require: ts-node/register

spec:
  - "test/**/*.spec.ts"
  - "test/**/global-hooks.ts"

watch-files:
  - "src/**/*.ts"
  - "test/**/*.spec.ts"

timeout: 5000
reporter: spec
recursive: true
exit: true
color: true
